"""
Django settings for chat_project project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
import firebase_admin
from firebase_admin import credentials
import logging

logger = logging.getLogger(__name__)

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# Channels configuration
ASGI_APPLICATION = "chat_project.asgi.application"


REDIS_URL = env("REDIS_URL", default="redis://redis:6379/0")
REDIS_SSL = REDIS_URL.startswith("rediss://")


# Use in-memory channel layer instead of Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "https://chatapp-production-2066.up.railway.app",
    ".railway.app",
    ".vercel.app",
    "chatapp-6k1l.onrender.com",
    ".onrender.com",
]

# Application definition
# Make sure 'rest_framework.authtoken' is in INSTALLED_APPS
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "channels",
    "chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chat_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chat_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Add this to your settings.py

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


CORS_ALLOW_CREDENTIALS = True

# For production, you should specify allowed origins instead of allowing all
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://chatapp-gamma-brown.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5500",
    "http://localhost:5500",
]

# If you need specific headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# If you need specific methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

STATIC_URL = "/static/"

# Location where static files will be collected
STATIC_ROOT = BASE_DIR / "staticfiles"

# Enable compression and caching support
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "chat.firebase_auth.FireBaseAuthBackend",
]


FIREBASE_CREDENTIALS_PATH = env(
    "FIREBASE_CREDENTIALS_PATH", default="chatterbox-admin-sdk.json"
)
FIREBASE_CREDENTIALS_FILE = Path(FIREBASE_CREDENTIALS_PATH)


def load_firebase_sdk_from_file(file_path):
    cred = credentials.Certificate(file_path)
    firebase_admin.initialize_app(cred)


def load_firebase_sdk_from_env(creds: dict):
    cred = credentials.Certificate(creds)
    firebase_admin.initialize_app(cred)


try:
    if FIREBASE_CREDENTIALS_FILE.exists():
        logger.warn("Firebase credentials file found at: %s", FIREBASE_CREDENTIALS_FILE)
        load_firebase_sdk_from_file(FIREBASE_CREDENTIALS_FILE)
        logger.warn("Firebase Admin initialized using credentials file.")
    else:
        # File doesn't exist, fall back to environment variables
        logger.warn(
            "Firebase credentials file not found at: %s", FIREBASE_CREDENTIALS_FILE
        )
        firebase_credentials = {
            "type": env("FIREBASE_TYPE", default=""),
            "project_id": env("FIREBASE_PROJECT_ID", default=""),
            "private_key_id": env("FIREBASE_PRIVATE_KEY_ID", default=""),
            "private_key": env("FIREBASE_PRIVATE_KEY", default="").replace("\\n", "\n"),
            "client_email": env("FIREBASE_CLIENT_EMAIL", default=""),
            "client_id": env("FIREBASE_CLIENT_ID", default=""),
            "auth_uri": env("FIREBASE_AUTH_URI", default=""),
            "token_uri": env("FIREBASE_TOKEN_URI", default=""),
            "auth_provider_x509_cert_url": env(
                "FIREBASE_AUTH_PROVIDER_X509_CERT_URL", default=""
            ),
            "client_x509_cert_url": env("FIREBASE_CLIENT_X509_CERT_URL", default=""),
        }
        load_firebase_sdk_from_env(firebase_credentials)
        logger.warn("Firebase Admin initialized using environment variables.")
except Exception as e:
    logger.error("Error when initializing the Firebase Admin application: %s", str(e))

AUTH_USER_MODEL = "chat.User"
